apiVersion: v1
kind: Service
metadata:
  name: svc-safc
spec:
  ports:
  - name: svc-safc-port
    nodePort: 31111
    port: 9001
    protocol: TCP
    targetPort: 8080
  selector:
    app: tickets
    club: safc
  type: NodePort
